from pydantic import BaseModel, Field
from typing import List, Optional

class ExplorationRequest(BaseModel):
    topic: str = Field(..., description="The main topic to explore", example="Quantum computing")

class ExplorationResponse(BaseModel):
    exploration_id: int = Field(..., description="The unique ID of the exploration graph")
    topic: str
    concepts: List[str] = Field(..., description="A list of 5 related concepts generated by the AI")

class NodeInfo(BaseModel):
    id: int
    title: str

class EdgeInfo(BaseModel):
    source: int
    target: int

class ExplorationGraphResponse(BaseModel):
    exploration_id: int
    topic: str
    nodes: List[NodeInfo]
    edges: List[EdgeInfo]
